export const INIT_NEW_GAME = 'INIT_NEW_GAME';
export const UPDATE_CURRENT_THROW = 'UPDATE_CURRENT_THROW';
export const PUSH_TO_CURRENT_LEG_THROWS = 'PUSH_TO_CURRENT_LEG_THROWS';
export const RESET_CURRENT_THROW = 'RESET_CURRENT_THROW';
export const SAVE_CURRENT_LEG_THROWS = 'SAVE_CURRENT_LEG_THROWS';
export const RESET_CURRENT_LEG_THROWS = 'RESET_CURRENT_LEG_THROWS';
export const UPDATE_PLAYER_SCORE = 'UPDATE_PLAYER_SCORE';
export const RESET_SCORES = 'RESET_SCORES';
export const UPDATE_AVERAGES = 'UPDATE_AVERAGES';
export const INCREMENT_TOTAL_THROW = 'INCREMENT_TOTAL_THROW';
export const UPDATE_BEST_THREE_DARTS = 'UPDATE_BEST_THREE_DARTS';
export const UPDATE_CHECKOUT_SCORE = 'UPDATE_CHECKOUT_SCORE';
export const UPDATE_SECTION_HIT = 'UPDATE_SECTION_HIT';
export const UPDATE_SCORE_RANGES = 'UPDATE_SCORE_RANGES';
export const UPDATE_DOUBLE_OUT = 'UPDATE_DOUBLE_OUT';
export const INCREMENT_LEG_WON = 'INCREMENT_LEG_WON';
export const RESET_PLAYER_LEG = 'RESET_PLAYER_LEG';
export const CHANGE_CURRENT_PLAYER = 'CHANGE_CURRENT_PLAYER';
export const CHANGE_STARTING_PLAYER_SET = 'CHANGE_STARTING_PLAYER_SET';
export const CHANGE_STARTING_PLAYER_LEG = 'CHANGE_STARTING_PLAYER_LEG';
export const INCREMENT_SET_WON = 'INCREMENT_SET_WON';
export const GAME_HAS_WINNER = 'GAME_HAS_WINNER';


export const SET_LOADING = 'SET_LOADING';

export const THROW_ERROR = 'THROW_ERROR';
export const RESET_ERROR = 'RESET_ERROR';